/**
 * The ./api folder is generated by `pnpm gen:sdk` command
 * Utilizing @nestia/sdk package.
 * 
 * @see {@link https://nestia.io/docs/sdk/sdk/}
 */
import api, { IConnection } from './api'
import { Filter, Search } from '@ativoscapital/jedi.node.core'

/**
 * Importing to use as types
 */
import * as InvoiceTypes from './api/functional'

export class InvoiceSdk {
  public connection: IConnection

  public http: typeof api.functional

  constructor(connection: IConnection) {
    this.connection = connection

    this.http = api.functional
  }
}

export { Filter, Search }

export type { InvoiceTypes }
